![Logo de NumPy](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=true)

## Introducción a NumPy

`NumPy` es un juego de palabras que significa **Python numérico** (*Numerical Python*). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

En concreto, las claves de esta librería son:

- **Array multidimensionales**: Esta librería proporciona un objeto llamado `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: NumPy permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para trabajar con arrays, incluyendo funciones trigonométricas, estadísticas, álgebra lineal, entre otras.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo. Además, es muy flexible en términos de acceso y manipulación de elementos individuales o subconjuntos de arrays.

NumPy es una biblioteca fundamental para el Machine Learning y la ciencia de los datos en Python. Proporciona una amplia gama de herramientas y funciones para trabajar eficientemente con datos numéricos en forma de arrays y matrices.

### Arrays

Un **array** de NumPy es una estructura de datos que permite almacenar una colección de elementos, generalmente números, en una o más dimensiones.

#### Array unidimensional

Un array unidimensional (1D) de NumPy es una estructura de datos que contiene una secuencia de elementos en una única dimensión. Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

![Array de una dimensión](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/1D.png?raw=true "1D")

Un array 1D puede ser creado usando la función `array` de la librería con una lista de elementos como argumento. Por ejemplo:

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

Esto creará un array 1D con los elementos 1, 2, 3, 4 y 5. Los elementos del array deben ser del mismo tipo de datos. Si los elementos son de diferentes tipos, NumPy intentará convertirlos al mismo tipo si es posible.

En un array 1D, podemos acceder a los elementos usando **índices** (*indexes*), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente. A continuación se muestran algunas operaciones que se pueden realizar utilizando el array anterior:

In [ ]:
# Acceder al tercer elemento
print(array[2])

# Cambiar el valor del segundo elemento
array[1] = 7
print(array)

# Sumar 10 a todos los elementos
array += 10
print(array)

# Calcular la suma de los elementos
sum_all = np.sum(array)
print(sum_all)

3
[1 7 3 4 5]
[11 17 13 14 15]
70


#### Array N-dimensional

Un array multidimensional o n-dimensional en NumPy es una estructura de datos que organiza elementos en múltiples dimensiones (ejes). Estos arrays permiten representar estructuras de datos más complejas, como matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

![Arrays de diferentes dimensiones](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/3D.png?raw=true "3D")

Un array N-dimensional puede ser creado también usando la función `array` de la librería. Por ejemplo, si queremos crear un array 2D:

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si ahora quisiéramos crear un array 3D, tendríamos que pensar en él como una lista de matrices:

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Al igual que sucedía con los arrays 1D, los elementos en un array multidimensional son accesibles mediante índices, se pueden realizar operaciones con ellos, etcétera.

A medida que agregamos más dimensiones, el principio básico sigue siendo el mismo: cada dimensión adicional puede considerarse como un nivel adicional de anidamiento. Sin embargo, a nivel práctico, trabajar con arrays de más de 3 o 4 dimensiones puede volverse más complejo y menos intuitivo.

Los arrays n-dimensionales en NumPy permiten una gran flexibilidad y potencia para representar y manipular datos en formas más complejas, especialmente útiles en campos como la ciencia de los datos, procesamiento de imágenes y aprendizaje profundo.

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera). Algunas de las más utilizadas en el análisis de datos son:

In [ ]:
import numpy as np

# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

# Operaciones Aritméticas
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

# Logarítmicas y Exponenciales
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

# Funciones Estadísticas
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

# Funciones de Redondeo
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## Ejercicios: Haz clic en "open in colab" para realizarlos

> Solución: https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy_solutions.ipynb

### Creación de arrays

#### Ejercicio 01:  Crea un **vector nulo** (*null vector*) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (`0`).

> NOTA: Revisa la función `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [2]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Ejercicio 03: Investiga la función `linspace` de NumPy y crea un array que contenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [4]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D (★★☆)

> NOTA: Revisa las funciones `np.random.rand` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html), `np.random.randint` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y `np.random.randn` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [12]:
np.random.rand(10)

array([0.88280135, 0.59016554, 0.47328887, 0.06352764, 0.58574901,
       0.21394864, 0.64561994, 0.98903134, 0.79282691, 0.14406384])

#### Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)


> NOTA: Revisa la función `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [11]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

> NOTA: Revisa la función `np.min` (https://numpy.org/devdocs/reference/generated/numpy.min.html) y `np.max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [16]:
m = np.random.rand(3,2)
print(m)
minimo = np.min(m)
maximo = np.max(m)
print(f'minimo =', minimo)
print(f'maximo =', maximo)


[[0.90203331 0.55181807]
 [0.88687127 0.05130133]
 [0.36843057 0.5587837 ]]
minimo = 0.051301327916139616
maximo = 0.9020333130588735


#### Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

> NOTA: Revisa la función `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [17]:
a = np.random.rand(30)
print(a)
media = np.mean(a)
print(f'media =', media)

[0.5450694  0.09055137 0.21168914 0.1279519  0.67688229 0.323951
 0.11965934 0.44617768 0.53306681 0.34109773 0.9571066  0.25661884
 0.95568334 0.84695653 0.2192776  0.44656522 0.40587202 0.97609157
 0.50116713 0.57056915 0.17797701 0.08893073 0.65956072 0.649058
 0.1884518  0.24958898 0.90970924 0.676257   0.02129224 0.46800668]
media = 0.45469456829937455


#### Ejercicio 08: Convierte la lista `[1, 2, 3]` y la tupla `(1, 2, 3)` en arrays (★☆☆)

In [18]:
lista = [1, 2, 3]
tupla = (1, 2, 3)
array_lista = np.array(lista)
array_tupla = np.array(tupla)

### Operaciones entre arrays

#### Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

> NOTA: Revisa la función `np.flip` (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [19]:
np.flip(array_lista)

array([3, 2, 1])

#### Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

> NOTA: Revisa la función `np.reshape` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [20]:
a = np.random.rand(5,12)
print(a)
b = np.reshape(a,(12,5))
print(b)


[[0.86800828 0.39220693 0.47135847 0.645202   0.2872492  0.40902702
  0.30834634 0.03490518 0.18948125 0.90890268 0.85245431 0.16854227]
 [0.99146242 0.44609226 0.25887482 0.79229178 0.16255675 0.2827328
  0.02542871 0.87457012 0.90519959 0.20411512 0.27364395 0.42841327]
 [0.47855185 0.50090719 0.56556537 0.61076965 0.78886392 0.32247845
  0.70889566 0.62135966 0.04645049 0.57674187 0.31076215 0.682491  ]
 [0.56806998 0.43357188 0.29808528 0.11101131 0.16615289 0.54324927
  0.68605284 0.39180959 0.22539774 0.36658437 0.76971466 0.04625622]
 [0.88433224 0.1972297  0.23155247 0.07736905 0.38032878 0.33415315
  0.80221567 0.18283964 0.03059458 0.2505853  0.05667706 0.09168012]]
[[0.86800828 0.39220693 0.47135847 0.645202   0.2872492 ]
 [0.40902702 0.30834634 0.03490518 0.18948125 0.90890268]
 [0.85245431 0.16854227 0.99146242 0.44609226 0.25887482]
 [0.79229178 0.16255675 0.2827328  0.02542871 0.87457012]
 [0.90519959 0.20411512 0.27364395 0.42841327 0.47855185]
 [0.50090719 0.56556537 0

#### Ejercicio 11: Convierte la lista `[1, 2, 0, 0, 4, 0]` en un array y obtén el índice de los elementos que no son cero (★★☆)

> NOTA: Revisa la función `np.where` (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [21]:
lista = [1, 2, 0, 0, 4, 0]
array = np.array(lista)
np.where(array != 0)

(array([0, 1, 4]),)

#### Ejercicio 12: Convierte la lista `[0, 5, -1, 3, 15]` en un array, multiplica sus valores por `-2` y obtén los elementos pares (★★☆)

In [22]:
lista = [0, 5, -1, 3, 15]
array = np.array(lista)
array = array * -2
array[array % 2 == 0]

array([  0, -10,   2,  -6, -30])

#### Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

> NOTA: Revisa la función `np.sort` (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [23]:
np.sort(np.random.rand(10))

array([0.13239693, 0.23718074, 0.36205906, 0.42383192, 0.4562929 ,
       0.51546235, 0.54596326, 0.62319413, 0.97964735, 0.98744369])

#### Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

> NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [24]:
a = np.random.rand(8)
b = np.random.rand(8)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[0.34170482 0.72822588 0.62546867 0.25219489 0.46009365 0.93149365
 0.85605545 0.2873292 ]
[0.79889945 0.17206723 0.63421677 0.87518148 0.65710941 0.70069765
 0.12983674 0.04100663]
[1.14060427 0.90029311 1.25968545 1.12737637 1.11720306 1.6321913
 0.98589219 0.32833583]
[-0.45719463  0.55615865 -0.0087481  -0.62298659 -0.19701577  0.230796
  0.72621871  0.24632257]
[0.27298779 0.12530381 0.39668272 0.2207163  0.30233187 0.65269541
 0.11114745 0.0117824 ]


#### Ejercicio 15: Convierte la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]` en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [25]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array = np.array(lista)
matriz = np.reshape(array,(3,4))
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])